#!/bin/bash


# variables
_apkdev=~/apk-devtool
_android_jar=$_apkdev/android-12/android.jar
_jks=$_apkdev/debug.keystore
_jks_pass="android"
_branch=main
_base=app/src/$_branch
_res=$_base/res
_java=$_base/java
_manifest=$_base/AndroidManifest.xml
# end

build(){
  case $1 in
    r*)
      _release=1
      ;;
    *)
      _release=0
      ;;
  esac

  rm -r build

  mkdir -p build/gen build/java build/dex build/obj

  cp $_apkdev/android-proguard-defaults build/android-proguard-defaults

  aapt2 compile --dir $_res -o build/obj

  if [ $_release -eq 1 ]; then
    aapt2 link -o build/output.unsigned.apk --manifest $_manifest --auto-add-overlay --java build/gen/ -I $_android_jar build/obj/*.flat --proguard build/proguard_options --proguard-minimal-keep-rules --no-xml-namespaces --override-styles-instead-of-overlaying --allow-reserved-package-id --no-version-vectors --no-auto-version --no-version-transitions --min-sdk-version 16 --target-sdk-version 32
  else
    aapt2 link -o build/output.unsigned.apk --manifest $_manifest --auto-add-overlay --java build/gen/ -I $_android_jar build/obj/*.flat --override-styles-instead-of-overlaying --allow-reserved-package-id --no-version-vectors --no-auto-version --no-version-transitions --min-sdk-version 16 --target-sdk-version 32
  fi

  _package=$(aapt2 dump packagename build/output.unsigned.apk | sed -r 's/[.]+/\//g')

  javac -cp $_android_jar $(find -name "*.java" | grep "$_java") build/gen/$_package/R.java -d build/java -target 11 -source 11

  if [ $_release -eq 1 ]; then
    r8 --dex --output build/dex/  --lib $_android_jar --pg-conf build/android-proguard-defaults --pg-conf build/proguard_options $(find -name "*.class" | grep "./build/java")
  else
    d8 --output build/dex/  --lib $_android_jar $(find -name "*.class" | grep "./build/java")
  fi

  cd build/dex/

  zip -ur ../output.unsigned.apk classes.dex

  cd ../..

  if [ $_release -eq 1 ]; then
    # optimize
    aapt2 optimize --shorten-resource-paths --collapse-resource-names --enable-sparse-encoding build/output.unsigned.apk -o build/output.optimized.apk

    zipalign -f -p 4 build/output.optimized.apk build/output.aligned.apk
  else
    zipalign -f -p 4 build/output.unsigned.apk build/output.aligned.apk
  fi

  apksigner sign -ks $_jks --ks-pass pass:$_jks_pass build/output.aligned.apk

  mv build/output.aligned.apk build/output.signed.apk
}

help(){
  echo -e "
apkdev is a development helper for building apks.

notice:
expected structure
\t<project-root>
\t  |-app/src/
\t     |-main/ (_branch) (_base)
\t       |-res/ (_res)
\t       |-java/ (_java)
\t       |-AndroidManifest.xml (_manifest)

\tto change the expected structure,
\tchange the variables in the script.
\t(ie. _branch, _java, etc.)

to use:
build
\tbuilds an apk.
\twipes and make a build/ directory for compiling.
\tcreate a apk as build/output.signed.apk
\tavailable options: release/debug
\trelease:
\t\tbuilds a release apk.
\t\thave optimization on.
\tdebug (default when no options):
\t\tbuilds a debug apk.
\t\tcontains debug info. 
\texecute command at <project-root>

new
\tcreate a new android project.
\thave a basic hello world setup.

help
\tprint this help message.
"
}

new(){
  echo "enter app name"
  read -p "> " _name
  echo "enter app package name"
  read -p "> " _package

  mkdir $_name

  cd $_name

  _package_dir=$(echo $_package | sed -r 's/[.]+/\//g')

  mkdir -p $_java/$_package_dir $_res/layout $_res/drawable $_res/values

  cp $_apkdev/ic_launcher.png $_res/drawable

  echo "<resources>
    <string name=\"app_name\">$_name</string>
</resources>"  > $_res/values/strings.xml
  echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
<LinearLayout xmlns:android=\"http://schemas.android.com/apk/res/android\"
  android:layout_width=\"match_parent\"
  android:layout_height=\"match_parent\">
	<TextView
     android:layout_width=\"wrap_content\"
     android:layout_height=\"wrap_content\"
     android:text=\"Hello World!\" />
</LinearLayout>" > $_res/layout/activity_main.xml


  echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\"
   android:versionCode=\"1\"
   android:versionName=\"1.0\"
   package=\"$_package\">

	<application
    android:theme=\"@android:style/Theme\"
    android:label=\"@string/app_name\"
    android:icon=\"@drawable/ic_launcher\">
		<activity android:name=\".MainActivity\"
       android:exported=\"true\">
			<intent-filter>
				<action android:name=\"android.intent.action.MAIN\" />
				<category android:name=\"android.intent.category.LAUNCHER\" />
			</intent-filter>
		</activity>
	</application>
</manifest>" > $_base/AndroidManifest.xml
  echo "package $_package;

import android.app.Activity;
import android.os.Bundle;

public class MainActivity extends Activity {

  protected void onCreate(Bundle bundle) {
    super.onCreate(bundle);
    this.setContentView(R.layout.activity_main);
  }
}
" > $_java/$_package_dir/MainActivity.java

  cd ..
  echo "done"
}

case $1 in
  b*)
    build
    ;;
  n*)
    new
    ;;
  *)
    help
    ;;
esac
