#!/bin/bash


# variables
_android_jar=~/apk-devtool/android-12/android.jar
_jks=~/apk-devtool/debug.keystore
_jks_pass="android"
_branch=main
_base=app/src/$_branch
_res=$_base/res
_java=$_base/java
_manifest=$_base/AndroidManifest.xml
# end


rm -r build

mkdir -p build/gen build/java build/dex build/obj

echo "
-dontskipnonpubliclibraryclasses
-allowaccessmodification
-verbose
-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod
-keep public class com.google.vending.licensing.ILicensingService
-keep public class com.android.vending.licensing.ILicensingService
-keep public class com.google.android.vending.licensing.ILicensingService
-dontnote com.android.vending.licensing.ILicensingService
-dontnote com.google.vending.licensing.ILicensingService
-dontnote com.google.android.vending.licensing.ILicensingService
-keepclasseswithmembernames class * {
    native <methods>;
}
-keepclassmembers public class * extends android.view.View {
    void set*(***);
    *** get*();
}
-keepclassmembers class * extends android.app.Activity {
    public void *(android.view.View);
}
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
-keepclassmembers class * implements android.os.Parcelable {
    public static final ** CREATOR;
}
-keepclassmembers class **.R$* {
    public static <fields>;
}
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}
-dontnote android.support.**
-dontnote androidx.**
-dontwarn android.support.**
-dontwarn androidx.**
-dontwarn android.util.FloatMath
-keep class android.support.annotation.Keep
-keep class androidx.annotation.Keep
-keep @android.support.annotation.Keep class * {*;}
-keep @androidx.annotation.Keep class * {*;}
-keepclasseswithmembers class * {
    @android.support.annotation.Keep <methods>;
}
-keepclasseswithmembers class * {
    @androidx.annotation.Keep <methods>;
}
-keepclasseswithmembers class * {
    @android.support.annotation.Keep <fields>;
}
-keepclasseswithmembers class * {
    @androidx.annotation.Keep <fields>;
}
-keepclasseswithmembers class * {
    @android.support.annotation.Keep <init>(...);
}
-keepclasseswithmembers class * {
    @androidx.annotation.Keep <init>(...);
}
-dontnote org.apache.http.**
-dontnote android.net.http.**
-dontnote java.lang.invoke.**
" > build/android-proguard-defaults

aapt2 compile --dir $_res -o build/obj

aapt2 link -o build/output.unsigned.apk --manifest $_manifest --auto-add-overlay --java build/gen/ -I $_android_jar build/obj/*.flat --proguard build/proguard_options --proguard-minimal-keep-rules --no-xml-namespaces --override-styles-instead-of-overlaying --allow-reserved-package-id --no-version-vectors --no-auto-version --no-version-transitions --min-sdk-version 16 --target-sdk-version 32

_package=$(aapt2 dump packagename build/output.unsigned.apk | sed -r 's/[.]+/\//g')

javac -cp $_android_jar $(find -name "*.java" | grep "$_java") build/gen/$_package/R.java -d build/java -target 11 -source 11

r8 --dex --output build/dex/  --lib $_android_jar --pg-conf build/android-proguard-defaults --pg-conf build/proguard_options $(find -name "*.class" | grep "./build/java")

cd build/dex/

zip -ur ../output.unsigned.apk classes.dex

cd ../..

# optimize
aapt2 optimize --shorten-resource-paths --collapse-resource-names --enable-sparse-encoding build/output.unsigned.apk -o build/output.optimized.apk

zipalign -f -p 4 build/output.optimized.apk build/output.aligned.apk

apksigner sign -ks $_jks --ks-pass pass:$_jks_pass build/output.aligned.apk

mv build/output.aligned.apk build/output.signed.apk
